import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const API_ROOT = "https://api.xstocks.fi/api/v2/public/assets";
const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(scriptDirectory, "..");
const outputPath = resolve(projectRoot, "data/assets.js");
const includePrices = !process.argv.includes("--skip-prices");

async function fetchJson(url, attempts = 3) {
  let lastError;
  for (let attempt = 1; attempt <= attempts; attempt += 1) {
    try {
      const response = await fetch(url, { headers: { Accept: "application/json" } });
      if (!response.ok) throw new Error(`${response.status} ${response.statusText}`);
      return await response.json();
    } catch (error) {
      lastError = error;
      if (attempt < attempts) await new Promise((resolveDelay) => setTimeout(resolveDelay, attempt * 900));
    }
  }
  throw new Error(`Failed ${url}: ${lastError?.message}`);
}

async function fetchAllAssets() {
  const assets = [];
  for (let page = 0; page < 100; page += 1) {
    const response = await fetchJson(`${API_ROOT}?page=${page}`);
    assets.push(...response.nodes);
    process.stdout.write(`Catalog page ${page + 1}: ${response.nodes.length} assets\n`);
    if (!response.page.hasNextPage) return assets;
  }
  throw new Error("Pagination exceeded the 100-page safety limit");
}

async function fetchPrices(assets, concurrency = 8) {
  const prices = new Map();
  let cursor = 0;

  async function worker() {
    while (cursor < assets.length) {
      const index = cursor;
      cursor += 1;
      const asset = assets[index];
      try {
        const response = await fetchJson(`${API_ROOT}/${encodeURIComponent(asset.symbol)}/price-data`, 2);
        prices.set(asset.symbol, Number.isFinite(response.quote) ? response.quote : null);
      } catch (error) {
        prices.set(asset.symbol, null);
        process.stderr.write(`Price unavailable for ${asset.symbol}: ${error.message}\n`);
      }
      if ((index + 1) % 100 === 0 || index + 1 === assets.length) {
        process.stdout.write(`Prices: ${index + 1}/${assets.length}\n`);
      }
    }
  }

  await Promise.all(Array.from({ length: concurrency }, worker));
  return prices;
}

function compactAsset(asset, prices) {
  return {
    symbol: asset.symbol,
    name: asset.name,
    logo: asset.logo,
    isin: asset.isin,
    underlyingSymbol: asset.underlying?.symbol || asset.underlyingSymbol || null,
    underlyingIsin: asset.underlying?.isin || asset.underlyingIsin || null,
    currency: asset.underlying?.currency || asset.trading?.currency || null,
    country: asset.underlying?.listingCountry || null,
    halted: Boolean(asset.isTradingHalted || asset.trading?.isTradingHalted),
    tradingMode: asset.trading?.tradingHoursMode || null,
    price: prices.get(asset.symbol) ?? null,
    exchange: asset.trading?.exchange ? {
      mic: asset.trading.exchange.mic,
      abbreviation: asset.trading.exchange.abbreviation,
      name: asset.trading.exchange.name,
      timezone: asset.trading.exchange.timezone,
    } : null,
    deployments: asset.deployments.map((deployment) => ({
      network: deployment.network,
      address: deployment.address,
      wrapperAddress: deployment.wrapperAddressV2 || null,
      atomic: Boolean(deployment.supportsAtomicSwaps),
    })).sort((a, b) => a.network.localeCompare(b.network)),
  };
}

function buildDataset(rawAssets, prices) {
  const assets = rawAssets
    .map((asset) => compactAsset(asset, prices))
    .sort((a, b) => a.symbol.localeCompare(b.symbol));
  const networkCounts = new Map();
  let totalDeployments = 0;

  for (const asset of assets) {
    for (const deployment of asset.deployments) {
      totalDeployments += 1;
      networkCounts.set(deployment.network, (networkCounts.get(deployment.network) || 0) + 1);
    }
  }

  const networks = [...networkCounts.entries()]
    .map(([name, count]) => ({ name, assets: count }))
    .sort((a, b) => b.assets - a.assets || a.name.localeCompare(b.name));

  return {
    meta: {
      generatedAt: new Date().toISOString(),
      source: API_ROOT,
      totalAssets: assets.length,
      totalDeployments,
      quotedAssets: assets.filter((asset) => Number.isFinite(asset.price)).length,
      networks,
    },
    assets,
  };
}

const rawAssets = await fetchAllAssets();
const prices = includePrices ? await fetchPrices(rawAssets) : new Map();
const dataset = buildDataset(rawAssets, prices);
const payload = `/* Generated by scripts/update-data.mjs from the official xStocks API. */\nwindow.XSTOCKS_DATA=${JSON.stringify(dataset)};\n`;

await mkdir(dirname(outputPath), { recursive: true });
await writeFile(outputPath, payload, "utf8");

process.stdout.write(`Wrote ${outputPath}\n`);
process.stdout.write(`${dataset.meta.totalAssets} assets, ${dataset.meta.networks.length} networks, ${dataset.meta.totalDeployments} deployments, ${dataset.meta.quotedAssets} quotes\n`);
